// ─── User & Auth ─────────────────────────────────────────────────────────────
export type UserRole = "admin" | "store_manager" | "pharmacist" | "viewer";

export interface User {
  uid: string;
  email: string;
  name: string;
  role: UserRole;
  phone?: string;
  hospitalId: string;
  createdAt: Date;
  lastLogin?: Date;
}

// ─── Hospital ─────────────────────────────────────────────────────────────────
export interface Hospital {
  id: string;
  name: string;
  address: string;
  phone: string;
  email: string;
  licenseNumber: string;
  createdAt: Date;
}

// ─── Medicine & Inventory ─────────────────────────────────────────────────────
export type HazardLevel = "high" | "medium" | "safe";
export type HazardType = "hazardous" | "hormonal" | "controlled" | "safe";
export type StockStatus = "in_stock" | "low_stock" | "critical" | "out_of_stock";
export type MedicineCategory =
  | "antibiotic"
  | "analgesic"
  | "antidiabetic"
  | "cardiovascular"
  | "hormonal"
  | "oncology"
  | "vaccine"
  | "cold_chain"
  | "controlled"
  | "general"
  | "other";

export interface Medicine {
  id: string;
  name: string;
  genericName: string;
  brand: string;
  category: MedicineCategory;
  formulation: string; // tablet, injection, syrup, etc.
  strength: string; // e.g. "500mg", "10mg/ml"
  unit: string; // tablets, vials, bottles
  hospitalId: string;

  // Hazard info
  hazardLevel: HazardLevel;
  hazardType: HazardType;
  hazardWarning?: string; // e.g. "Use gloves", "Avoid direct contact"

  // Stock info
  totalQuantity: number;
  reorderLevel: number;
  reorderQuantity: number;
  maxStockLevel: number;
  status: StockStatus;

  // Pricing
  unitPrice: number; // INR
  mrp: number;

  // Storage
  storageCondition: "room_temp" | "refrigerated" | "frozen" | "controlled";
  temperatureMin?: number;
  temperatureMax?: number;

  // Metadata
  supplierId?: string;
  drugCode?: string; // internal code
  barcode?: string;
  isCritical: boolean; // life-saving drug flag
  isScheduled: boolean; // controlled substance

  createdAt: Date;
  updatedAt: Date;
}

// ─── Batch ────────────────────────────────────────────────────────────────────
export interface Batch {
  id: string;
  medicineId: string;
  medicineName: string;
  batchNumber: string;
  quantity: number;
  remainingQuantity: number;
  manufacturingDate: Date;
  expiryDate: Date;
  purchasePrice: number;
  mrp: number;
  supplierId: string;
  grnId: string;
  receivedDate: Date;
  storageLocation?: string;
  hospitalId: string;

  // Status
  isExpired: boolean;
  daysToExpiry: number;
  expiryStatus: "safe" | "near_expiry" | "critical" | "expired";
}

// ─── Dispensing ───────────────────────────────────────────────────────────────
export interface DispensingLog {
  id: string;
  medicineId: string;
  medicineName: string;
  batchId: string;
  batchNumber: string;
  quantity: number;
  dispensedBy: string; // user id
  dispensedByName: string;
  patientId?: string;
  patientName?: string;
  prescriptionId?: string;
  notes?: string;
  hospitalId: string;
  dispensedAt: Date;
}

// ─── Supplier ─────────────────────────────────────────────────────────────────
export interface Supplier {
  id: string;
  name: string;
  contactPerson: string;
  phone: string;
  email: string;
  address: string;
  licenseNumber: string;
  gstNumber?: string;
  rating: number; // 1-5
  isActive: boolean;
  hospitalId: string;
  createdAt: Date;
}

// ─── Purchase Order ───────────────────────────────────────────────────────────
export type POStatus = "pending" | "approved" | "sent" | "received" | "cancelled";

export interface PurchaseOrderItem {
  medicineId: string;
  medicineName: string;
  quantity: number;
  unitPrice: number;
  totalPrice: number;
}

export interface PurchaseOrder {
  id: string;
  poNumber: string;
  supplierId: string;
  supplierName: string;
  items: PurchaseOrderItem[];
  totalAmount: number;
  status: POStatus;
  isAutoGenerated: boolean;
  requestedBy: string;
  approvedBy?: string;
  expectedDelivery?: Date;
  hospitalId: string;
  createdAt: Date;
  updatedAt: Date;
}

// ─── GRN ─────────────────────────────────────────────────────────────────────
export interface GRNItem {
  medicineId: string;
  medicineName: string;
  orderedQty: number;
  receivedQty: number;
  batchNumber: string;
  expiryDate: Date;
  unitPrice: number;
}

export interface GRN {
  id: string;
  grnNumber: string;
  poId: string;
  supplierId: string;
  supplierName: string;
  items: GRNItem[];
  totalAmount: number;
  receivedBy: string;
  invoiceNumber?: string;
  hospitalId: string;
  receivedAt: Date;
}

// ─── Alert ───────────────────────────────────────────────────────────────────
export type AlertType =
  | "low_stock"
  | "expiry"
  | "critical_drug"
  | "fraud"
  | "temperature"
  | "auto_order"
  | "compliance"
  | "transfer";
export type AlertSeverity = "critical" | "warning" | "info";
export type AlertStatus = "active" | "acknowledged" | "resolved";

export interface Alert {
  id: string;
  type: AlertType;
  severity: AlertSeverity;
  title: string;
  message: string;
  medicineId?: string;
  medicineName?: string;
  batchId?: string;
  status: AlertStatus;
  smsSent: boolean;
  emailSent: boolean;
  hospitalId: string;
  createdAt: Date;
  resolvedAt?: Date;
}

// ─── Stock Transaction ────────────────────────────────────────────────────────
export type TransactionType =
  | "received"
  | "dispensed"
  | "adjusted"
  | "returned"
  | "disposed"
  | "transferred";

export interface StockTransaction {
  id: string;
  type: TransactionType;
  medicineId: string;
  medicineName: string;
  batchId: string;
  quantityBefore: number;
  quantityChange: number;
  quantityAfter: number;
  reason?: string;
  performedBy: string;
  performedByName: string;
  hospitalId: string;
  createdAt: Date;
}

// ─── ML Prediction ────────────────────────────────────────────────────────────
export interface DemandPrediction {
  medicineId: string;
  medicineName: string;
  predictedDemand: number; // units per month
  currentStock: number;
  daysUntilStockout: number;
  confidenceScore: number; // 0-1
  reorderSuggested: number;
  reorderByDate: Date;
}

export interface WastePrediction {
  medicineId: string;
  medicineName: string;
  batchId: string;
  expiryDate: Date;
  currentQuantity: number;
  predictedUsage: number;
  predictedWasteQty: number;
  predictedWasteValue: number;
  riskLevel: "high" | "medium" | "low";
}

// ─── Temperature / Cold Chain ─────────────────────────────────────────────────
export interface TemperatureReading {
  id: string;
  zone: string;
  temperature: number;
  humidity?: number;
  isBreached: boolean;
  hospitalId: string;
  recordedAt: Date;
}

// ─── KPIs ─────────────────────────────────────────────────────────────────────
export interface DashboardKPIs {
  totalStockValue: number; // INR
  totalItems: number;
  expiringSoon: number; // < 30 days
  lowStockCount: number;
  outOfStockCount: number;
  expiryWastageValue: number;
  forecastAccuracy: number; // %
  inventoryTurnoverRate: number;
  stockEfficiency: number; // %
  pendingOrders: number;
  fraudAlerts: number;
}

// ─── Notification Contact ─────────────────────────────────────────────────────
export interface NotificationContact {
  userId: string;
  name: string;
  role: UserRole;
  phone: string;
  email: string;
  smsEnabled: boolean;
  emailEnabled: boolean;
  alertTypes: AlertType[];
}

// ─── Inter-Hospital Transfer ──────────────────────────────────────────────────
export type TransferStatus = "suggested" | "approved" | "in_transit" | "received" | "rejected";

export interface HospitalTransfer {
  id: string;
  fromHospitalId: string;
  toHospitalId: string;
  fromHospitalName: string;
  toHospitalName: string;
  medicineId: string;
  medicineName: string;
  quantity: number;
  reason: string;
  status: TransferStatus;
  isAIsuggested: boolean;
  createdAt: Date;
  updatedAt: Date;
}
