// ─── Mock Data for UI Demo ────────────────────────────────────────────────────
// Replace with real Firebase data once backend is connected

import type { Medicine, Batch, Alert, DispensingLog, DashboardKPIs, DemandPrediction } from "@/types";

export const mockKPIs: DashboardKPIs = {
  totalStockValue: 2463500,
  totalItems: 847,
  expiringSoon: 47,
  lowStockCount: 12,
  outOfStockCount: 3,
  expiryWastageValue: 84200,
  forecastAccuracy: 91.4,
  inventoryTurnoverRate: 4.2,
  stockEfficiency: 87.3,
  pendingOrders: 8,
  fraudAlerts: 2,
};

export const mockMedicines: Medicine[] = [
  {
    id: "med001",
    name: "Insulin Glargine",
    genericName: "Insulin Glargine",
    brand: "Lantus",
    category: "antidiabetic",
    formulation: "Injection",
    strength: "100U/ml",
    unit: "vials",
    hospitalId: "hosp001",
    hazardLevel: "high",
    hazardType: "hormonal",
    hazardWarning: "⚠️ Hormonal – Avoid direct contact",
    totalQuantity: 45,
    reorderLevel: 50,
    reorderQuantity: 200,
    maxStockLevel: 500,
    status: "critical",
    unitPrice: 820,
    mrp: 950,
    storageCondition: "refrigerated",
    temperatureMin: 2,
    temperatureMax: 8,
    isCritical: true,
    isScheduled: false,
    barcode: "8901234567890",
    createdAt: new Date("2024-01-15"),
    updatedAt: new Date("2024-03-10"),
  },
  {
    id: "med002",
    name: "Amoxicillin 500mg",
    genericName: "Amoxicillin",
    brand: "Mox",
    category: "antibiotic",
    formulation: "Capsule",
    strength: "500mg",
    unit: "strips",
    hospitalId: "hosp001",
    hazardLevel: "safe",
    hazardType: "safe",
    totalQuantity: 1240,
    reorderLevel: 200,
    reorderQuantity: 500,
    maxStockLevel: 2000,
    status: "in_stock",
    unitPrice: 12,
    mrp: 15,
    storageCondition: "room_temp",
    isCritical: false,
    isScheduled: false,
    barcode: "8901234567891",
    createdAt: new Date("2024-01-20"),
    updatedAt: new Date("2024-03-12"),
  },
  {
    id: "med003",
    name: "Morphine Sulfate",
    genericName: "Morphine",
    brand: "Morphine",
    category: "controlled",
    formulation: "Injection",
    strength: "10mg/ml",
    unit: "ampoules",
    hospitalId: "hosp001",
    hazardLevel: "high",
    hazardType: "hazardous",
    hazardWarning: "⚠️ Hazardous – Use gloves",
    totalQuantity: 28,
    reorderLevel: 20,
    reorderQuantity: 50,
    maxStockLevel: 100,
    status: "in_stock",
    unitPrice: 145,
    mrp: 180,
    storageCondition: "controlled",
    isCritical: true,
    isScheduled: true,
    barcode: "8901234567892",
    createdAt: new Date("2024-02-01"),
    updatedAt: new Date("2024-03-15"),
  },
  {
    id: "med004",
    name: "Metformin 500mg",
    genericName: "Metformin",
    brand: "Glycomet",
    category: "antidiabetic",
    formulation: "Tablet",
    strength: "500mg",
    unit: "strips",
    hospitalId: "hosp001",
    hazardLevel: "safe",
    hazardType: "safe",
    totalQuantity: 89,
    reorderLevel: 100,
    reorderQuantity: 300,
    maxStockLevel: 600,
    status: "low_stock",
    unitPrice: 8,
    mrp: 12,
    storageCondition: "room_temp",
    isCritical: false,
    isScheduled: false,
    barcode: "8901234567893",
    createdAt: new Date("2024-02-10"),
    updatedAt: new Date("2024-03-18"),
  },
  {
    id: "med005",
    name: "Adrenaline 1mg",
    genericName: "Epinephrine",
    brand: "Epinephrine",
    category: "cardiovascular",
    formulation: "Injection",
    strength: "1mg/ml",
    unit: "ampoules",
    hospitalId: "hosp001",
    hazardLevel: "high",
    hazardType: "hazardous",
    hazardWarning: "⚠️ Hazardous – Use gloves",
    totalQuantity: 156,
    reorderLevel: 50,
    reorderQuantity: 100,
    maxStockLevel: 300,
    status: "in_stock",
    unitPrice: 48,
    mrp: 65,
    storageCondition: "room_temp",
    isCritical: true,
    isScheduled: false,
    barcode: "8901234567894",
    createdAt: new Date("2024-01-25"),
    updatedAt: new Date("2024-03-20"),
  },
];

export const mockAlerts: Alert[] = [
  {
    id: "alert001",
    type: "expiry",
    severity: "critical",
    title: "Insulin Glargine Expiring Soon",
    message: "200 units of Insulin Glargine (Batch B-2024-01) expire in 3 days. Immediate action required.",
    medicineId: "med001",
    medicineName: "Insulin Glargine",
    status: "active",
    smsSent: true,
    emailSent: true,
    hospitalId: "hosp001",
    createdAt: new Date(),
  },
  {
    id: "alert002",
    type: "low_stock",
    severity: "warning",
    title: "Metformin 500mg — Low Stock",
    message: "Stock level (89 strips) is below reorder level (100). Consider placing a purchase order.",
    medicineId: "med004",
    medicineName: "Metformin 500mg",
    status: "active",
    smsSent: true,
    emailSent: false,
    hospitalId: "hosp001",
    createdAt: new Date(Date.now() - 3600000),
  },
  {
    id: "alert003",
    type: "fraud",
    severity: "critical",
    title: "⚠️ Suspicious Dispensing Detected",
    message: "10 units of Morphine removed without billing record. Possible unauthorized access.",
    medicineId: "med003",
    medicineName: "Morphine Sulfate",
    status: "active",
    smsSent: true,
    emailSent: true,
    hospitalId: "hosp001",
    createdAt: new Date(Date.now() - 7200000),
  },
  {
    id: "alert004",
    type: "critical_drug",
    severity: "critical",
    title: "Adrenaline: Critical Drug Monitor",
    message: "Adrenaline 1mg is flagged as life-saving. Current stock is adequate but requires daily verification.",
    medicineId: "med005",
    medicineName: "Adrenaline 1mg",
    status: "acknowledged",
    smsSent: false,
    emailSent: false,
    hospitalId: "hosp001",
    createdAt: new Date(Date.now() - 86400000),
  },
];

export const mockDispensingLogs: DispensingLog[] = [
  { id: "d1", medicineId: "med001", medicineName: "Insulin Glargine", batchId: "b1", batchNumber: "B-2024-01", quantity: 5, dispensedBy: "u1", dispensedByName: "Dr. Priya Sharma", patientName: "Ramesh Kumar", hospitalId: "hosp001", dispensedAt: new Date(Date.now() - 1800000) },
  { id: "d2", medicineId: "med002", medicineName: "Amoxicillin 500mg", batchId: "b2", batchNumber: "B-2024-02", quantity: 14, dispensedBy: "u2", dispensedByName: "Dr. Amit Verma", patientName: "Sunita Devi", hospitalId: "hosp001", dispensedAt: new Date(Date.now() - 3600000) },
  { id: "d3", medicineId: "med004", medicineName: "Metformin 500mg", batchId: "b4", batchNumber: "B-2024-04", quantity: 30, dispensedBy: "u1", dispensedByName: "Dr. Priya Sharma", patientName: "Vikash Singh", hospitalId: "hosp001", dispensedAt: new Date(Date.now() - 7200000) },
  { id: "d4", medicineId: "med005", medicineName: "Adrenaline 1mg", batchId: "b5", batchNumber: "B-2024-05", quantity: 2, dispensedBy: "u3", dispensedByName: "Dr. Anita Rao", patientName: "Emergency Case", hospitalId: "hosp001", dispensedAt: new Date(Date.now() - 10800000) },
];

export const mockDemandPredictions: DemandPrediction[] = [
  { medicineId: "med001", medicineName: "Insulin Glargine", predictedDemand: 180, currentStock: 45, daysUntilStockout: 7, confidenceScore: 0.94, reorderSuggested: 200, reorderByDate: new Date(Date.now() + 3 * 86400000) },
  { medicineId: "med004", medicineName: "Metformin 500mg", predictedDemand: 320, currentStock: 89, daysUntilStockout: 8, confidenceScore: 0.88, reorderSuggested: 300, reorderByDate: new Date(Date.now() + 2 * 86400000) },
  { medicineId: "med002", medicineName: "Amoxicillin 500mg", predictedDemand: 450, currentStock: 1240, daysUntilStockout: 83, confidenceScore: 0.91, reorderSuggested: 500, reorderByDate: new Date(Date.now() + 60 * 86400000) },
];

export const stockUsageChartData = [
  { date: "Mar 1", units: 245 }, { date: "Mar 3", units: 312 }, { date: "Mar 5", units: 287 },
  { date: "Mar 7", units: 398 }, { date: "Mar 9", units: 356 }, { date: "Mar 11", units: 421 },
  { date: "Mar 13", units: 389 }, { date: "Mar 15", units: 445 }, { date: "Mar 17", units: 412 },
  { date: "Mar 19", units: 378 }, { date: "Mar 21", units: 467 },
];

export const expiryTimelineData = [
  { week: "This Week", count: 8, value: 12400 },
  { week: "Next Week", count: 15, value: 28600 },
  { week: "2 Weeks", count: 24, value: 43200 },
  { week: "1 Month", count: 47, value: 84200 },
  { week: "3 Months", count: 112, value: 198400 },
];

export const categoryBreakdownData = [
  { name: "Antibiotics", value: 28, color: "#0EA5E9" },
  { name: "Antidiabetic", value: 22, color: "#10B981" },
  { name: "Cardiovascular", value: 18, color: "#1E3A8A" },
  { name: "Analgesics", value: 15, color: "#F59E0B" },
  { name: "Hormonal", value: 10, color: "#8B5CF6" },
  { name: "Others", value: 7, color: "#64748B" },
];
